### ISSUE TITLE
.GP 파일 수집 스크립트

### ISSUE THREAD

**Issue by usa6463** [usa6463/IntelligentDrumBeat#2]
기타프로 타브악보 사이트 -> http://guitarprotabs.org/
위 사이트에서 .gp 파일들 다 수집할 수 있는 스크립트 필요.

드럼파트 없는 악보, 버전이 안맞는 .gp 파일 등은 추후에 처리.

**Comment by aleaflet** [comment]
우선 전부수집하는 스크립트는 작성완료
